name: gitlab-ce
icon: gitlab
title: GitLab Community Edition

services:
- name: gitlab
  title: GitLab Community Edition
  service: gitlab:19
  required: true
  main: true
  links:
  - name: postgres
    service: postgres
  - name: redis
    service: valkey
  - name: sendmail
    service: opensmtpd
  volumes:
  - name: repositories
    size: 50

- name: runner
  title: GitLab Runner
  service: gitlab-runner:19
  disabled: true
  links:
  - name: gitlab
    service: gitlab

- name: postgres
  title: PostgreSQL
  service: postgres:17
  required: true
  env:
  - name: POSTGRES_DB
    value: '{{database.db.name}}'
  - name: POSTGRES_DB_EXTENSIONS
    value: amcheck,btree_gist,pg_trgm
  - name: POSTGRES_MAX_CONNECTIONS
    value: '400'
  - name: POSTGRES_SHARED_BUFFERS
    value: 2GB
  - name: POSTGRES_WORK_MEM
    value: 8MB
  - name: POSTGRES_MAINTENANCE_WORK_MEM
    value: 128MB
  workloads:
  - name: main
    containers:
    - name: postgresql
      resources:
        request:
          cpu: 500
          memory: 2560
        limit:
          cpu: 2000
          memory: 4096
  volumes:
  - name: data
    size: 20

- name: valkey
  title: Valkey
  service: valkey:8.1
  required: true
  volumes:
  - name: data
    size: 10

- name: opensmtpd
  title: OpenSMTPD
  service: opensmtpd:7
  required: true
